name: Build and Deploy Django to cPanel via FTP

on:
  push:
    branches:
      - main   # Runs only when you push to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Django (migrate + collectstatic)
      run: |
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput

    - name: Prepare build folder
      run: |
        mkdir build
        cp -r portfolio main manage.py requirements.txt build/
        cp -r staticfiles build/

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: build/
        server-dir: / # change to your actual cPanel path
        dangerous-clean-slate: true
